global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "express-app"
    static_configs:
      - targets: ["app:5050"]
  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"]
      - targets: ["otel-collector:8888"]
