apiVersion: 1

datasources:
  - name: Prometheus + Otel
    type: prometheus
    url: http://prometheus:9090
    editable: true
  - name: Loki
    type: loki
    url: http://loki:3100
    editable: true
